"""Add completed_at, is_completed, priority to PlannerTask

Revision ID: 03d1c1190943
Revises: 
Create Date: 2025-01-19 13:23:51.212603

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '03d1c1190943'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payment_methods', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last4', sa.String(length=4), nullable=False))
        batch_op.drop_column('last_four')

    with op.batch_alter_table('planner_tasks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('completed_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('is_completed', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('priority', sa.String(length=20), nullable=False))
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('planner_tasks', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
        batch_op.drop_column('priority')
        batch_op.drop_column('is_completed')
        batch_op.drop_column('completed_at')

    with op.batch_alter_table('payment_methods', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_four', sa.VARCHAR(length=4), nullable=False))
        batch_op.drop_column('last4')

    # ### end Alembic commands ###
